name: Publish GitHub release
on: [push]

jobs:
   

  rebuild:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Create the rootfs
        if: contains(steps.needs_update.outputs.stdout, 'rebuild is needed')
        run: |
          ${{ github.workspace }}/build-rootfs.sh

      - name: Get the short version of the last commit
        id: vars
        run: echo "tag_name=$(cat artifacts/debian_12_slim.tar.gz.sha256|cut -c 1-8)" >> $GITHUB_OUTPUT

      - name: Create the GH release
        if: contains(steps.needs_update.outputs.stdout, 'rebuild is needed')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/artifacts/*
          tag_name: ${{ steps.vars.outputs.tag_name }}

